### ISSUE TITLE
ledgereth.exceptions.LedgerError: Unexpected error: 0x6983 UNKNOWN

### ISSUE THREAD

**Issue by KoliosterNikolayIliev** [mikeshultz/ledger-eth-lib#29]
Hi,

I have been experiencing the following problem with Ledger nano s plus.

After command "python -m ledgereth accounts" in CLI and also any time trying to access ledger device  following exception is risen 
(ledgereth.exceptions.LedgerError: Unexpected error: 0x6983 UNKNOWN).
Problem occurred after updating ledger firmware to 1.0.4.

Devices with older version of firmware do not experience this error.

Device data:
model: Ledger nano s plus
Firmware version: 1.0.4
Ethereum app version: 1.10.0  
Polygon app version: 1.10.0 

Cheers,

**Comment by mikeshultz** [comment]
Taking a quick look, it looks like [this error code was introduced recently in this PR](https://github.com/LedgerHQ/app-ethereum/pull/339).  Looks like APDU size checking.  Assuming that's right, maybe this lib is sending the wrong length in the request?  I'll get my ledger upgraded and check this out later tonight when I have some time.

Thanks for the report, I appreciate it.

**Comment by mikeshultz** [comment]
So I was able to reproduce your issue and was able to fix account fetching.  However, it appears the issue of `Lc` being incorrect is a little more widespread and the only reason we got away with it before was because app-ethereum was generally pleasant about it.  Their recent update added strict checking and throws an error if it sees something unexpected.

I'm going to need to spend a little more time on this and go through the full test suite and fix any issues I find.  Will update this issue as I go.

**Comment by KoliosterNikolayIliev** [comment]
Thanks for the fast response. :+1:

**Comment by KoliosterNikolayIliev** [comment]
Thanks for the fast response. :+1:

**Comment by mikeshultz** [comment]
@KoliosterNikolayIliev just released v0.7.3.  Should fix your issues.  If it doesn't, please open a new issue.  Thanks again for the report.

- https://github.com/mikeshultz/ledger-eth-lib/releases/tag/v0.7.3
- https://pypi.org/project/ledgereth/0.7.3/
