### ISSUE TITLE
Install issues (from ledgerblue)

### ISSUE THREAD

**Issue by antazoey** [mikeshultz/ledger-eth-lib#35]
I tried install on macos and am getting this error:

```
      wheel.vendored.packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
          python-pyscard>=1.6.12-4build1
                        ~~~~~~~~~~^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ledgerblue
  Running setup.py clean for ledgerblue
Failed to build ledgerblue
ERROR: Could not build wheels for ledgerblue, which is required to install pyproject.toml-based projects

```

**Comment by mikeshultz** [comment]
@antazoey could you provide repro steps?

**Comment by mikeshultz** [comment]
Relevant commit in ledgerblue: https://github.com/LedgerHQ/blue-loader-python/commit/3316c15c3615e38d552009b041081e73ae870a92

Looks to be due to a setuptools breaking change: https://setuptools.pypa.io/en/stable/history.html#v67-0-0

Upgrading our ledgerblue dep should take care of this.  Though I'd like to batch this in with the updates in #34 to add support for newer Python versions.
