### ISSUE TITLE
Unable to have gas price of 0

### ISSUE THREAD

**Issue by antazoey** [mikeshultz/ledger-eth-lib#39]
Some dev networks allows gas price of 0 but when I try it here, I get 

```
  File .../ledger-eth-lib/ledgereth/transactions.py", line 217, in create_transaction
    raise ValueError("gas_price or max_fee_per_gas must be provided")
ValueError: gas_price or max_fee_per_gas must be provided
```

The code is:

```python
    # we need a gas price for a valid transaction
    if not gas_price and not max_fee_per_gas:
        raise ValueError("gas_price or max_fee_per_gas must be provided")
```

it probably should be 

```python
    # we need a gas price for a valid transaction
    if gas_price is None and max_fee_per_gas is None:
        raise ValueError("gas_price or max_fee_per_gas must be provided")
```

**Comment by antazoey** [comment]
I have verified this fixes is my issue

**Comment by mikeshultz** [comment]
I had no idea 0 gas price was valid.  Good to know, thanks.  

Making this change has some other implications as well. The defaults are hinky, then since they're all `0`:

https://github.com/mikeshultz/ledger-eth-lib/blob/0b15b559182682c5e0eec3fb8acc3edff590460d/ledgereth/transactions.py#L159-L161

Maybe `gas_price` should default to `None` and the others as `0` but in `create_transaction()` that would mean it would fallback to a type 0 transaction:

https://github.com/mikeshultz/ledger-eth-lib/blob/0b15b559182682c5e0eec3fb8acc3edff590460d/ledgereth/transactions.py#L220

Probably want to default them all to `None` then and then do some shitty logic checking for access lists to make sure it's not a type 1 tx before setting a default gas price or max fee. Or just use defaults at object instantiation...

**Comment by mikeshultz** [comment]
Thinking about it a bit, if `gas_price` and `max_fee_per_gas` is zero, a type 0 tx would be just fine anyway.  We should just remove that check, then.  EZ
